spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://localhost:8084/workshop?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver

server:
  contextPath : /workshop